### ISSUE TITLE
Issue #4 : Incorrect details in /history command

### ISSUE THREAD

**Issue by JayProngs** [hrmauny/slashbot#4]
Details and header doesn't match.
<img width="613" alt="Screenshot 2023-10-11 at 10 06 29 PM" src="https://github.com/hrmauny/slashbot/assets/38587156/251fea57-e1c9-48c7-98b5-acd0815a9e5a">

**Comment by hrmauny** [comment]
only the headers are wrong or details under the headers are wrong as well?

**Comment by JayProngs** [comment]
Just the order is wrong. Ideally it should be Food-10/09/23-$ 10.00.

**Comment by harshmauny** [comment]
Can you check now

**Comment by JayProngs** [comment]
Working fine. Closing the issue.
